language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

<<<<<<< HEAD
#before_script:
=======

#before_script:
 # - npm install -g gulp

>>>>>>> 3843b3c2c515ca7dd9540e6af929de19d8ba6f36
script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "binbing"
  - git config user.email "759761612@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: git@github.com:binbing/binbing.github.io.git
